CREATE TABLE CLIENT(
  ID            INTEGER         NOT NULL,
  CLIENT_NAME   VARCHAR(255)    NOT NULL,
  ACTIVE        CHAR(1)         NOT NULL  DEFAULT 'Y'
);

 CREATE SEQUENCE CLIENT_SEQUENCE_ID START WITH (select max(ID) + 1 from CLIENT);